import React, { useState } from 'react';
import { Sparkles, MessageSquare, Filter } from 'lucide-react';
import { UserProfile, Recommendation } from '../../types';
import { RecommendationCard } from '../common/RecommendationCard';

interface InsightsViewProps {
  userProfile: UserProfile;
  recommendations: Recommendation[];
  onNavigateTab: (tab: string) => void;
  onOpenAskDrawer: (initialQuery?: string) => void;
}

export const InsightsView: React.FC<InsightsViewProps> = ({
  userProfile,
  recommendations,
  onNavigateTab,
  onOpenAskDrawer,
}) => {
  const [selectedFilter, setSelectedFilter] = useState<'all' | 'save' | 'borrow' | 'grow' | 'goals'>('all');

  const filteredRecommendations = recommendations.filter((rec) => {
    if (selectedFilter === 'all') return true;
    return rec.category.toLowerCase() === selectedFilter;
  });

  return (
    <div className="space-y-8 pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-indigo-600">
            Intelligent Advisory
          </span>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-[#1A1F2C] mt-1">
            Insights & Action Plan
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            Comprehensive, 5-step actionable recommendations generated by FinWise to guide your money decisions.
          </p>
        </div>

        <button
          type="button"
          id="ask-finwise-insights-btn"
          onClick={() => onOpenAskDrawer('Explain my current financial health score')}
          className="px-4 py-2.5 rounded-xl bg-indigo-50 text-indigo-700 hover:bg-indigo-100 border border-indigo-200 text-xs sm:text-sm font-semibold transition-colors flex items-center gap-2 self-start sm:self-auto shadow-xs"
        >
          <MessageSquare className="w-4 h-4 text-indigo-600" />
          <span>Ask FinWise a Question</span>
        </button>
      </div>

      {/* Filter Chips */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1">
        <Filter className="w-4 h-4 text-gray-400 shrink-0 ml-1" />
        {(['all', 'save', 'borrow', 'grow', 'goals'] as const).map((filter) => (
          <button
            key={filter}
            type="button"
            id={`filter-insight-${filter}`}
            onClick={() => setSelectedFilter(filter)}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold capitalize transition-all shrink-0 ${
              selectedFilter === filter
                ? 'bg-indigo-600 text-white shadow-xs'
                : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
            }`}
          >
            {filter === 'all' ? 'All Insights' : filter}
          </button>
        ))}
      </div>

      {/* Recommendations Grid (5-Step UX Pattern) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredRecommendations.map((rec) => (
          <div key={rec.id} className="relative">
            <RecommendationCard
              recommendation={rec}
              onActionClick={(tab) => onNavigateTab(tab)}
            />
            <div className="mt-2 text-right">
              <button
                type="button"
                onClick={() => onOpenAskDrawer(`Tell me more about: ${rec.title}`)}
                className="text-[11px] font-semibold text-gray-500 hover:text-indigo-600 inline-flex items-center gap-1"
              >
                <Sparkles className="w-3 h-3 text-indigo-500" />
                <span>Ask AI to clarify this recommendation</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Philosophy Banner */}
      <div className="p-5 rounded-2xl bg-gray-50 border border-gray-200 text-xs text-gray-600 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div>
          <p className="font-bold text-[#1A1F2C]">5-Step Advisory Standard</p>
          <p className="text-gray-500 mt-0.5">
            Every FinWise action plan breaks down Your Situation, What FinWise Noticed, Recommended Action, The Underlying Why, and What Happens Next.
          </p>
        </div>
        <button
          type="button"
          onClick={() => onNavigateTab('dashboard')}
          className="text-xs font-semibold text-indigo-600 hover:underline shrink-0"
        >
          Return to Dashboard
        </button>
      </div>
    </div>
  );
};
